services:
  backend:
    build: ./backend
    container_name: fraud_backend
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/fraud_detection
      - REDIS_URL=redis://cache:6379/0
      - QDRANT_URL=http://vector_db:6333
    depends_on:
      - db
      - cache
      - vector_db
    networks:
      - fraud_net

  frontend:
    build: ./frontend
    container_name: fraud_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - fraud_net

  db:
    image: postgres:16-alpine
    container_name: fraud_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fraud_detection
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fraud_net

  vector_db:
    image: qdrant/qdrant:latest
    container_name: fraud_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - fraud_net

  cache:
    image: redis:7-alpine
    container_name: fraud_redis
    ports:
      - "6380:6379"
    networks:
      - fraud_net

networks:
  fraud_net:
    driver: bridge

volumes:
  postgres_data:
  qdrant_data:
